sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.25.2
  FLASK_ENV: development

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - export REACT_APP_USERS_SERVICE_URL=http://127.0.0.1
  - docker-compose up -d --build

script:
  - docker-compose exec users pytest "project/tests" -p no:warnings
  - docker-compose exec users flake8 .
  - dc exec users black . --check --exclude=migrations
  - dc exec users /bin/sh -c "isort ./*/*/*.py --check-only --filter-files"
  - dc exec client react-scripts test --coverage --watchAll=false

after_script:
  - docker-compose down
