sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.25.2
  FLASK_ENV: development

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` -o > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose up -d --build

script:
  - docker-compose exec users pytest "project/tests" -p no:warnings
  - docker-compose exec users flake8 .
  - docker-compose exec users black . --check
  - docker-compose exec users /bin/sh -c "isort ./*/*/*.py --check-only"

after_script:
  - docker-compose down
