sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.25.4
  FLASK_ENV: development
  USERS_CACHE_IMAGE: viliusgudziunas/goals-app-users
  CLIENT_CACHE_IMAGE: viliusgudziunas/goals-app-client

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker pull $USERS_CACHE_IMAGE:latest || true
  - docker pull $CLIENT_CACHE_IMAGE:latest || true
  - export REACT_APP_USERS_SERVICE_URL=http://127.0.0.1
  - npm install

script:
  - bash test.sh ci

after_success:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  - docker push $USERS_CACHE_IMAGE:latest
  - docker push $CLIENT_CACHE_IMAGE:latest
