'''empty message

Revision ID: 932b99577b49
Revises: 
Create Date: 2020-01-31 23:44:41.786137

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932b99577b49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
